name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsque vous poussez sur la branche 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy Helm chart
      run: |
        helm upgrade --install my-app ./path-to-your-chart --namespace my-app-namespace --values ./path-to-your-chart/values.yaml

