name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube  # Crée le dossier .kube s'il n'existe pas
        echo "${{ secrets.KUBECONFIG }}" | base64 --decode > ~/.kube/config  # Décode le secret base64 et le place dans ~/.kube/config

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Deploy Helm chart
      run: |
        helm upgrade --install my-app ./helm/first-app --namespace my-app-namespace --values ./helm/first-app/values.yaml

